# -*- coding: utf-8 -*-
"""q1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XVSqQj0A74jh1tUjcXrA0oHgwzu0t44f
"""

import matplotlib.pyplot as plt

# Measurements for each group
group_A = [12, 15, 14, 13, 16, 18, 19, 15, 14, 20, 17, 14, 15,40,45,50,62]
group_B = [12, 17, 15, 13, 19, 20, 21 ,18 ,17 ,16 ,15 ,14 ,16 ,15]

# Create a figure with two subplots
fig = plt.figure(figsize=(10.5 if len(group_A) > len(group_B) else (9 if len(group_A) == len(group_B) else (8.5)),6))

ax1 = fig.add_subplot(121)
ax2 = fig.add_subplot(122)

# Box plot for Group A
ax1.boxplot(group_A)
ax1.set_title('Box Plot of Group A')
ax1.set_ylabel('Measurement Values')

# Box plot for Group B
ax2.boxplot(group_B)
ax2.set_title('Box Plot of Group B')
ax2.set_ylabel('Measurement Values')

# Overall figure title
fig.suptitle('Comparison of Measurement Distributions in Groups A and B')

# plt.tight_layout(rect=[0.01 if len(str(max(max(group_A), max(group_B)))) <4 else (0.02),
#                        # Adjusting the layout based on the maximum value length to prevent overlap.
#                        # This adjustment might need tuning depending on specific data ranges.
#                        # For simplicity and assuming typical values won't exceed three digits,
#                        # we use a basic approach here.

#                       None,
#                       None,
#                       .95])

plt.show()

