# -*- coding: utf-8 -*-
"""q2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XVSqQj0A74jh1tUjcXrA0oHgwzu0t44f
"""

import numpy as np
import matplotlib.pyplot as plt

# Read genome sequence from file
with open('genome.txt', 'r') as f:
    genome_sequence = f.read().strip()

# Convert sequence into list
genome_list = list(genome_sequence)

# Find length of genome
genome_length = len(genome_list)

# Define color mapping for each nucleotide
color_map = {
    'A': 'red',
    'T': 'blue',
    'C': 'green',
    'G': 'yellow'
}

# Generate coordinates for helix structure
t = np.linspace(0, 4 * np.pi, len(genome_list))
x = np.cos(t)
y = np.sin(t)
z = np.linspace(0, 5, len(genome_list))

coordinates = np.column_stack((x, y, z))

# Create colors array based on color map
colors_array = [color_map[nucleotide] for nucleotide in genome_sequence]

# Plotting setup
fig = plt.figure(figsize=(8,8))
ax3d = fig.add_subplot(projection='3d')

ax3d.scatter(x[:], y[:], z[:], c=colors_array)

ax3d.set_xlabel('X')
ax3d.set_ylabel('Y')
ax3d.set_zlabel('Z')

plt.title("Helix Structure Representation")
plt.show()